### ISSUE TITLE
[Feature] todo list command behavior

### ISSUE THREAD

**Issue by nextuponstream** [nextuponstream/todo#1]
- [x] add `--all|-a` to display all todo lists (current behavior), even the ones with all tasks done
**Motivation**: This would help create archives to look back on while not cluttering todo list
- [x] add `--done|-d` to display only done tasks
- [x] add `--short|-s` which displays title, and labels of todo's
**Motivation**: `todo list` becomes cluttered rapidly with only 2-3 todo's. It also help providing a good overview of what needs to be done by filtering unnecessary information.

**Comment by nextuponstream** [comment]
short : ff3dbac440a6da0649e41b9752851e42e213f447

**Comment by nextuponstream** [comment]
all+done: dd6ac06
