### ISSUE TITLE
depth of section parsing

### ISSUE THREAD

**Issue by nextuponstream** [nextuponstream/todo#25]
- [ ] Parse a section that is 3, 4, 5... level of heading
Currently only 3
- [ ] Select a subsection within a subsection
given
```markdown
# Title

## Task list

### Not interesting section

#### Subsection

* [ ] don't parse this

### Section

#### Subsection

* [ ] do parse this
``` 
then
```
todo list -t title -so --section Section --subsection Subsection
Todo lists from /home/path/to/todos/category
# task-list
## Section
### Subsection
* [ ] do parse this
```
